### ISSUE TITLE
Assign Error in jquery.dajax.core.js

### ISSUE THREAD

**Issue by jonathonadler** [jorgebastida/django-dajax#1]
Hi,

I have an error assigning a value using dajax with jquery:

example command:
    dajax = Dajax()
    dajax.assign('#example','value', random.randint(1, 10))
    return dajax.json()

I traced it down to jquery.dajax.core.js. The clear_quotes funtion doesn't exist:

```
            case 'as':
                elem.val = clear_quotes(elem.val);
                jQuery.each($(elem.id),function(){ this[elem.prop] = elem.val; });
```

**Comment by jorgebastida** [comment]
Thanks for the report jonathonadler,
That function was removed along time ago.

http://github.com/jorgebastida/django-dajax/commit/5b54b302c09be2ad055b45e5b5de8ca890313621
