### ISSUE TITLE
get_media_prefix  exception in example

### ISSUE THREAD

**Issue by scurtu** [jorgebastida/django-dajax#10]
Hi. I am new to django and very new to dajax, I want to ask you for some help.

I installed to run the examples of django-dajax (download the archive dajax-examples.tar.gz), and tried to  run it using command python manager.py runserver

In every example I get the same error:

Caught an exception while rendering: 'module' object has no attribute 'get_media_prefix'

Can anybody help me?
I think I've installed something wrongly or something is missing.
Thank you very much

**Comment by jorgebastida** [comment]
Can you share your django-dajax and django-dajaxice version?

Thanks!

**Comment by jorgebastida** [comment]
No feedback since 9 month. Closed
