### ISSUE TITLE
Support for UTF8

### ISSUE THREAD

**Issue by yanoksy** [jorgebastida/django-dajax#11]
Could not be used with Spanish or other language with accents.

**Comment by jorgebastida** [comment]
Can you share some code to reproduce the error. (Traceback, example... something)
Thanks!

**Comment by bernie2004** [comment]
replace escape into encodeURIComponent in dajaxice  / templates  / dajaxice  / dajaxice.core.js line 10:
send_data.push('argv='+encodeURIComponent(JSON.stringify(argv)));

at least that's what works for me

**Comment by jnohlgard** [comment]
Works like a charm!
See also: http://xkr.us/articles/javascript/encode-compare/
escape() encodes everything to its iso8859-1 representation, which is a bad choice since Django uses unicode internally.

**Comment by jorgebastida** [comment]
Fixing this bug in dajaxice. Will be released in django-dajaxice-0.1.5

**Comment by jorgebastida** [comment]
Doesn't fixed in 0.1.5 , i will reopen the ticket and fix it.
