### ISSUE TITLE
Problems with add_css_class and remove_css_class

### ISSUE THREAD

**Issue by muckz** [jorgebastida/django-dajax#12]
Today I tried dajax and found it very usefull. I use jquery 1.4 and therefore jquery.dajax.core.js. The add_css_class and remove_css_class function did not work, all other functions did work. 
After a bit of testing I found that changing the function from:
    jQuery.each(elem.val,function(){
        $(elem.id).addClass(this);
     });
to:
    jQuery.each(elem.val,function(){
        $(elem.id).addClass(""+this+"");
     });
did solve the problem. The same change did work for the remove_css_class function.

**Comment by jorgebastida** [comment]
Fixed! http://github.com/jorgebastida/django-dajax/commit/1af8a3c40fcd5dd4e607268650a9e40ed9c4702a

Thanks!
