### ISSUE TITLE
form example does not work with IE

### ISSUE THREAD

**Issue by doneal24** [jorgebastida/django-dajax#19]
Running Internet Explorer 7 on WinXP.  Most of my client base will be running this version and upgrading is not possible.  The form at http://dajaxproject.com/forms/ allows the user to select a country but the second dropdown showing cities does not update.  Form does work with other browsers.

**Comment by doneal24** [comment]
I should have read the closed calls before posting this one.  It is an IE problem and the other calls pointed me in the right direction.  For the benefit of others who are stuck with IE,  the following changes will get the form working with IE:
ajax.py:

def updatecombo(request, option):
    dajax = Dajax()
    options = [ ['Madrid','Barcelona','Vitoria','Burgos'],
        ['Paris','Evreux','Le Havre','Reims'],
        ['London','Birmingham','Bristol','Cardiff'],]
    out = ""
    for o in options[int(option)]:
        out = "%s<option value='#'>%s" % (out,o,)

```
ua = request.META['HTTP_USER_AGENT']
if ua.find('MSIE') > 0 or ua.find('msie') > 0:
    out = '<select name="combo2" id="combo2">%s</select>' % out
    dajax.assign('#MSIE', 'innerHTML', out)
else:
    dajax.assign('#combo2','innerHTML',out)

return dajax.json()
```

HTML:
<select name="combo1" id="combo1" onchange="Dajaxice.examples.updatecombo(Dajax.process,{'option':this.value})" size="1">
<option value="0">Select...</option>
<option value="0">Spain</option>
<option value="1">France</option>
<option value="2">United Kingdom</option>
</select>

<div id="MSIE"><select name="combo2" id="combo2" onchange="" size="1"></select></div>

**Comment by antivir** [comment]
This does not work for me.
I have:
1. Prototype: does work in FF but not in IE
2. jQuery 1.51: does not work both FF and IE.
Any solutions?

**Comment by maldn** [comment]
Hi,
i just fixed this issue in our application.
The problem is, that IE can't set the "innerHTML" property of select-nodes.
Our solution/workaround is to simply send javascript.
Instead of:

```
 dajax.assign('#my_id','innerHTML', my_html)
```

use (if you use jquery)

```
 js = '$("#my_id").html("%s")' % my_html
 dajax.script(js)
```

**Comment by antivir** [comment]
Thank you, but I'm on Rails now...
