### ISSUE TITLE
dajaxproject.com online examples and Django 1.2.5

### ISSUE THREAD

**Issue by mntnoe** [jorgebastida/django-dajax#20]
None of the online examples at djangoproject.com works at the moment:

<pre><code>Uncaught TypeError: Object 
...
&lt;div id="summary"&gt;
  &lt;h1&gt;Forbidden &lt;span&gt;(403)&lt;/span&gt;&lt;/h1&gt;
  &lt;p&gt;CSRF verification failed. Request aborted.&lt;/p&gt;
...</code></pre>

The reason is a backwards incompatible change in Django 1.2.5 that requires AJAX requests to be CSRF protected too.

See here: http://docs.djangoproject.com/en/1.2/releases/1.2.5/#csrf-exception-for-ajax-requests

**Comment by jorgebastida** [comment]
Ups! Fixed :)

El sábado 2 de abril de 2011, mntnoe
reply@reply.github.com
escribió:
