### ISSUE TITLE
Jquery Addcc/remcc Chromium bug

### ISSUE THREAD

**Issue by jorgebastida** [jorgebastida/django-dajax#23]
Just a quick bug report: Chromium was interpeting these lines from
jquery.dajax.core.js incorrectly:

$(elem.id).addClass(this);
$(elem.id).removeClass(this);

It was not resolving "this" as a string, and instead passed "this"
into the function as a reference. I added a manual ".toString()" that
resolved the problem:

$(elem.id).addClass(this.toString());
$(elem.id).removeClass(this.toString());

Thanks Chase [1]

[1] http://groups.google.com/group/dajaxproject/browse_thread/thread/f32fc197d534dd39

**Comment by jorgebastida** [comment]
Unreproducible error

**Comment by asmer** [comment]
I've reproduce this bug:

chromium 14.0.835.163 and firefox 6
