### ISSUE TITLE
'Dajax' object has no attribute 'json'

### ISSUE THREAD

**Issue by hanglihl** [jorgebastida/django-dajax#24]
HELLO,

I met following issue when i try to use dajax:

Traceback (most recent call last):

  File ... in process
    response = '%s(%s)' % ( callback, thefunction(self.request, **argv) )

  File ,,,  line 37, in join
    return dajax.json()

AttributeError: 'Dajax' object has no attribute 'json'

Coud you give me any hint on it?

Thanks

**Comment by jorgebastida** [comment]
Hi hanglihl,

It seems that you are using an old django-dajax version.
Can you share what version are you using?

Thanks

**Comment by hanglihl** [comment]
Yes you are right. After I updated the dajax, everythingworks fine. Thanks :)
