### ISSUE TITLE
unicode(data) error

### ISSUE THREAD

**Issue by hardwoodmarble** [jorgebastida/django-dajax#25]
Where: /dajax/core/dajax.py line 85
What: This should be changed to unicode(data, 'utf8')
Why: Causes encoding problems (UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position _: ordinal not in range(128) ) when given certain characters. The function is trying to decode to ascii before encoding to unicode, because that is the default. Thus, my change would have it use utf8 instead of ascii as the decoder before the unicode encodes.

:D

**Comment by jorgebastida** [comment]
0.9.2 Released http://pypi.python.org/pypi/django-dajax/0.9.2
