### ISSUE TITLE
'dajax_templatetags' is not a valid tag library

### ISSUE THREAD

**Issue by gmolino** [jorgebastida/django-dajax#26]
Hi all. I have the message "'dajax_templatetags' is not a valid tag library" executing the dajax-examples refering to the first line in the template. I installed dajax and dajaxice following instructions. I would grateful for any tip.

**Comment by jorgebastida** [comment]
There isn't a dajax_templatetags. It's dajaxice_templatetags.

You must add dajaxice to your INSTALLED_APPS.

**Comment by gmolino** [comment]
Thank for your answer. The message error not appear but, without any mistake, don't running the dajax. I would like download the dajax-examples.tar.gz file but it seems broken. Could you repair it? 
Thank you again.

**Comment by gmolino** [comment]
I am sorry, I solved the problem updating files with repositories. Anyway, congratulation on your project.
