### ISSUE TITLE
dajaxice_callback should be a function since dajaxice 0.2

### ISSUE THREAD

**Issue by bluekite2000** [jorgebastida/django-dajax#27]
I m running your examples on my local machine and receive the pop up error. when I select some country in Ajax Form Machine!
The error is 

dajaxice_callback should be a function since dajaxice 0.2

I installed django-dajax and  django-dajaxice using pip.
The only thing I changed in the examples code is in settings.py, where I added 'dajax' to INSTALLED_APPS
Please help.

**Comment by jorgebastida** [comment]
Hi bluekite2000,

The problem is that django-dajaxice-0.2 doesn't allow callbacks as strings and Dajax 0.8 examples weren't updated when I release that version. I've fixed the problem in master and I'll release a new version soon.

Thanks!

**Comment by metazool** [comment]
Today I'm having the same problem ( dajaxice as used in the All Colours Are Beautiful project https://github.com/muccc/acabed/ )

I guess this issue was fixed but don't see updates to the files after this conversation?
