### ISSUE TITLE
Could jQuery 1.3.2+ be supported?

### ISSUE THREAD

**Issue by semanty** [jorgebastida/django-dajax#28]
Just a newbie for dajax, it seems Jquery 1.5.1 not support well

**Comment by jorgebastida** [comment]
Hi semanty,

Can you provide me more info about the errors you have using jQuery 1.5.1?

I've just tested it and runs ok.

Thanks

**Comment by semanty** [comment]
Really thanks for your help. I now try to use ajax through jquery directly. In fact, since beginning, dajaxice and dajax confused me a lot.
