### ISSUE TITLE
PEP8 compliance

### ISSUE THREAD

**Issue by hcarvalhoalves** [jorgebastida/django-dajax#3]
Would be good to have PEP8 [1] compliance regarding naming style.

Code like:
    dajax.removeCSSClass(...)

Breaks the common naming style of both Python [1] and Django [2]. According to PEP8, the recommendation would be:

```
dajax.remove_css_class(...)
```

I know it's down to personal preference, but surely makes Dajax alien in the middle of a PEP8 compliant, Django project. If it ever made into Django contrib, this would have to be fixed too, so I think it's a great idea to get this right from the beginning.

[1] http://www.python.org/dev/peps/pep-0008/

[2] http://docs.djangoproject.com/en/dev/internals/contributing/#coding-style

**Comment by jorgebastida** [comment]
Fixed in HEAD
Thanks !

**Comment by hcarvalhoalves** [comment]
Good. Thank you!
