### ISSUE TITLE
[DAJAX] Example form doesn't work on IE

### ISSUE THREAD

**Issue by GreMaory** [jorgebastida/django-dajax#30]
Hi,

When i was testing your project, i see a problem on this page http://www.dajaxproject.com/forms/

IE is strict : It can't modify the innerHtml of select and other element such as tr, td etc...

Thx

**Comment by haridas** [comment]
I had the same issue with select on IE. I fix this by using the basic javascript dom element construction. ie; try to use bellow methods while constructing dynamic elements on DOM.

document.createElement, document.childNode, document.createTextNode, etc...

hope this will help you.

**Comment by abadger1406** [comment]
See same issue on IE 8 .. could someone be specific on how this demo can be modified to support IE 8.

Thx Dave

**Comment by jorgebastida** [comment]
0.9.2 Released http://pypi.python.org/pypi/django-dajax/0.9.2
