### ISSUE TITLE
Pagination does not work on IE8

### ISSUE THREAD

**Issue by crazyscientist** [jorgebastida/django-dajax#31]
Hi,
I have a little Wiki running on Django 1.3.1 with Dajaxice 0.2 and Dajax 0.8.4.
Everything is running fine on Firefox, Chrome and Opera. By accident I discovered this little problem with IE8:

I have implemented the Pagination example from http://dajaxproject.com/pagination/. In order to avoid CSRF token issues I got rid of the tokens in views that have Paginations.

IE8 gives the following error message:
Unbekannter Laufzeitfehler  (approx. "Unknown runtime error")
prototype.dajax.core.js
line: 23
code: 0
char: 50
URI: http://www-elektronenmikroskopie.uni-regensburg.de/media/js/dajax/prototype.dajax.core.js

I'm not sure whether this is an issue solely caused by Dajax because the Pagination example on http://dajaxproject.com/pagination/ is working fine.

I would appreciate any ideas...

**Comment by jorgebastida** [comment]
0.9.2 Released http://pypi.python.org/pypi/django-dajax/0.9.2
