### ISSUE TITLE
Update documentation examples

### ISSUE THREAD

**Issue by dbrgn** [jorgebastida/django-dajax#32]
The "simple form example" in the [online documentation](http://dajaxproject.com/forms/) should be updated to reflect changes in [the example code](https://github.com/jorgebastida/django-dajax/blob/master/dajaxexamples/examples/ajax.py#L51), not only because of the code style, but also because the `+=` in the loop creates a bug in the HTML generation.

**Comment by jorgebastida** [comment]
I've rewrite http://dajaxproject.com completely and opensourced it's code instead of adding it to django-dajax. This should be fixed now.

Cheers!
