### ISSUE TITLE
Error in the javascript dajax.

### ISSUE THREAD

**Issue by vinigracindo** [jorgebastida/django-dajax#34]
The firebug is pointing in the following javascript errors:
jquery.dajax.core.js - $ is undefined $.each(data, function(i,elem){
prototype.dajax.core.js - Class is not defined var Dajax = Class.create();
mootools.dajax.core.js - data.each is not a function data.each(function(elem){
dojo.dajax.core.js - dojo is not defined dojo.forEach(data, function(elem,i){

**Comment by jorgebastida** [comment]
You shouldn't be including all the backends, only one. Choose a JS framework and include the appropiate.
