### ISSUE TITLE
Does dajax support django 1.4

### ISSUE THREAD

**Issue by abadger1406** [jorgebastida/django-dajax#36]
ImproperlyConfigured at /maps/
Error importing template source loader django.template.loaders.filesystem.load_template_source: "'module' object has no attribute 'load_template_source'

I guess this has something to do with the following...

Function-based template loaders
Django 1.2 changes the template loading mechanism to use a class-based approach. Old style function-based template loaders will still work, but should be updated to use the new class-based template loaders.

Is this something that can easily be updated ?

**Comment by LaundroMat** [comment]
Hi, you should just comment out 'django.template.loaders.app_directories.load_template_source' in your TEMPLATE_LOADERS settings.

`django.template.loaders.app_directories.load_template_source` states that 

```
 "'django.template.loaders.app_directories.load_template_source' is deprecated; use 'django.template.loaders.app_directories.Loader' instead.",
```
