### ISSUE TITLE
Setting Dajax with JQuery

### ISSUE THREAD

**Issue by victorjabur** [jorgebastida/django-dajax#37]
I'm using jqueryui on my site. When i install Dajax, it works, but it broken all my jqueryui layout.

How can i make for this works ?

I didn't find any documentation about to use Dajax with JQuery.

Can you help me ?

**Comment by bleib1dj** [comment]
Are you by chance using the prototype implementation instead of JQuery? If in your header you have something like:

```
<script src="http://www.google.com/jsapi"></script>
<script>
    google.load("prototype", "1.6.0.3");
</script>
<script src="{% static 'js/prototype.dajax.core.js' %}" type="text/javascript" charset="utf-8"></script>
```

instead of:

```
<script src="http://www.google.com/jsapi"></script>
<script>
    google.load("jquery", "1.7.2");
</script>
<script src="{% static 'js/jquery.dajax.core.js' %}" type="text/javascript" charset="utf-8"></script>
```

It will end up breaking your JQuery UI.
