### ISSUE TITLE
Dajax - Support events Jquery

### ISSUE THREAD

**Issue by vinigracindo** [jorgebastida/django-dajax#38]
I wanted to put a loading.gif while the ajax with Jquery is being processed, but he does not call the events of jquery. I as follows:

$("select#id_estado.select_black_style").change(function() {
   $(document).ajaxStart(function(){
    $("#teste").show();
    });
    $(document).ajaxStop(function(){
    $("#teste").hide();
    });
    Dajaxice.apps.localizacao.updatecombo_estadocidade(Dajax.process,{"option":this.value});
    return false;
});

This does not work.

**Comment by jorgebastida** [comment]
Dajaxice doesn't use jQuery at all, it use http://code.google.com/p/xmlhttprequest/ to do all the asynchronous communication. A workaround could be:

``` javascript
$("select#id_estado.select_black_style").change(function() {
    $("#teste").show();
    Dajaxice.apps.localizacao.updatecombo_estadocidade(function(data){
        $("#teste").hide();
        Dajax.process(data);
    }, {"option": this.value});
    return false;
});

```

Cheers!
