### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in _clean method

### ISSUE THREAD

**Issue by spoof** [jorgebastida/django-dajax#4]
When i use localized data in my forms with Dajax i get error:

<pre>
  UnicodeEncodeError: 'ascii' codec can't encode characters 
</pre>

in dajax/core/Dajax.py on _clean(self, data):

<pre>
   return str(data).replace('\n','').replace('\r','')
</pre>

Maybe it should use 'unicode()' instead of 'str()' ?

**Comment by jorgebastida** [comment]
Hello spoof,
Probably your fix will solve the problem, but can you share some example to reproduce the problem?

**Comment by spoof** [comment]
Hello,

It happens when dajax returns data and this data contains with non ascii chars. In my example i use default &lt;option&gt;&lt;/option&gt; tag with {% trans %} template tag:

ajax.py:

<pre>
def ajax_selectbox(request, _id):
  dajax = Dajax()
  objs = SomeModel.objects.filter(id=_id)
  out = render_to_string('template.html', {'objs' : objs})
  dajax.assign('#options', 'innerHTML', out)
  return dajax.json()
</pre>

template.html:

<pre>
{% load i18n %}
&lt;option value=""&gt;{% trans "Please select model" %}&lt;/option&gt;
....
</pre>

**Comment by jorgebastida** [comment]
After some testing, seems to work well. Changes will be released in 0.8.4

**Comment by jorgebastida** [comment]
Fixed in dajaxice-0.1.3
