### ISSUE TITLE
Error in Django Forms example?

### ISSUE THREAD

**Issue by toasterleavings** [jorgebastida/django-dajax#42]
Hello, and thanks for your hard work on these libraries

Not a core issue, but in the full forms example at http://www.dajaxproject.com/fullform/
 I believe there's an error in the send_form() function provided:

``` javascript
function send_form(){
      data = $('my_form').serialize(true);
      Dajaxice.examples.send_form(Dajax.process,{'form':data});
}
```
- 'my_form' should be '#my_form' ? Working through the example was less than fruitfull till I added the #.

Cheers

**Comment by jorgebastida** [comment]
Hello @toasterleavings,

I've release a new version of django-dajax and django-dajaxice as well as a full new http://dajaxproject.com site fixing hundreds of errors. This page source code is now opensource here: https://github.com/jorgebastida/dajaxproject.com

Cheers
