### ISSUE TITLE
jquery.html() like function

### ISSUE THREAD

**Issue by schacki** [jorgebastida/django-dajax#43]
Hi all,
would it make sense, is it possible to add a html() like function.
This would enable us to replace/add certain parts of the documents out of Django Templates.
Thanks
Juergen

**Comment by jorgebastida** [comment]
Hello @schacki 
You mean change browser html using a rendered template?

```
from django.shortcuts import render
from dajax.core import Dajax
from dajaxice.decorators import dajaxice_register

@dajaxice_register
def render_example(request):
    dajax = Dajax()
    dajax = Dajax()
    dajax.assign('#element', 'innerHTML', render(request, 'your_template.html'))
    return dajax.json()
```

Hope this helps you.
