### ISSUE TITLE
unicode throws exception 

### ISSUE THREAD

**Issue by geladriet** [jorgebastida/django-dajax#46]
Setup:
- Django 1.4.1
- PostgreSQL with UTF-8

When querying a table with all countries for selection this error is thrown: 

---

return unicode(data).replace('\n','').replace('\r','')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2115: ordinal not in range(128)
response: DAJAXICE_EXCEPTION

---

The problem is the unicode command in django.py (http://docs.python.org/howto/unicode.html)

---

```
def _clean(self, data):
    if hasattr(data,'__iter__'):
        return map(self._clean,data)
    else:
        try:
            return unicode(data).replace('\n','').replace('\r','')
        except Exception: # Used to avoid the exception 
            return data; # Used to avoid the exception 
```

---

This is a quick and dirty fix, I have no idea if it is a good idea to do this.

**Comment by jorgebastida** [comment]
For the next release I'm going to remove this _clean method, currently is quite pointless and it's also breaking <textareas> content.

Thanks!

**Comment by jorgebastida** [comment]
Fixed on develop, ready for 0.9.2

**Comment by jorgebastida** [comment]
0.9.2 Released http://pypi.python.org/pypi/django-dajax/0.9.2

**Comment by geladriet** [comment]
Thanks a lot! :)
