### ISSUE TITLE
Typo in script(code) documentation

### ISSUE THREAD

**Issue by imrekel** [jorgebastida/django-dajax#47]
The example in the documentation has code() instead of script():

```
def code_example(request):
    dajax = Dajax()
    dajax.code('my_function();')
    return dajax.json()
```

**Comment by jorgebastida** [comment]
Fixed @kenley 
https://github.com/jorgebastida/django-dajax/commit/23dd0e22d85ade68fb19a2a80ee497426438236a

Thanks!
