### ISSUE TITLE
Two problems with examples on the web page

### ISSUE THREAD

**Issue by gerdemb** [jorgebastida/django-dajax#5]
1. The example here http://dajaxproject.com/fullform/ doesn't show the definition of send_form() I had to look at the page source to see the Dajaxice.examples.send_form() command
2. The example here http://dajaxproject.com/forms/ doesn't work in Internet Explorer. Not really a dajax bug, but still confusing. Here's a discussion of the issue: http://stackoverflow.com/questions/1293427/innerhtml-replace-does-not-reflect

**Comment by jorgebastida** [comment]
First of all thank you for the feedback.
1. the send_form() definition added in the example page
2. thanks for the advise, but dajax itself can't do anything. The example only tries to represent an easy way to modify the DOM. This cross browsing issues should be faced particularly in each development. Sorry

**Comment by jorgebastida** [comment]
Site upgraded
