### ISSUE TITLE
Typo in documentation.

### ISSUE THREAD

**Issue by Arussil** [jorgebastida/django-dajax#57]
Hi,
the example of script() is written as:

dajax.code('my_function();')

instead of:

dajax.script('my_function();')

**Comment by sframe** [comment]
Came here to report the same issue.

See: http://django-dajax.readthedocs.org/en/latest/api.html#script-code

Example wouldn't work:

``` python
from dajax.core import Dajax

def code_example(request):
    dajax = Dajax()
    dajax.code('my_function();')
    return dajax.json()

```

Until I changed it to:

``` python
from dajax.core import Dajax

def code_example(request):
    dajax = Dajax()
    dajax.script('my_function();')
    return dajax.json()

```

**Comment by ChrisFreeman** [comment]
I also came here to report this issue, and even forked the repo to submit a fix... until I saw there already was a pull request with this fixed: [See Pull 51](https://github.com/jorgebastida/django-dajax/pull/51)
