### ISSUE TITLE
Encoding problem

### ISSUE THREAD

**Issue by gerdemb** [jorgebastida/django-dajax#7]
Not sure if this is a dajax or JavaScript problem.

I am sending serialized form data data to my ajax function like this:

```
    form_data = $('#email-form').serialize(false);
    Dajaxice.escola.build_emails('Dajax.process',{'form_data':form_data});
```

and receiving the data like this:

def build_emails(request, form_data=None):
    dajax = Dajax()

but in this case form_data is None and I get the following error:

ERROR:root:DAJAXICE argv exception Unterminated string starting at: line 1 column 13 (char 13)

the correct value of form_data should be something like "to_func=on&additional=&subject=&message=" I found that adding this line to my JavaScript fixed the problem:

```
    form_data = encodeURIComponent(form_data);
```

Interestingly, I didn't have to add a corresponding urldecode function to my ajax function as the passed form_data is already decoded automatically somehow

**Comment by jorgebastida** [comment]
Dajaxice javascript arguments must me in an object format that will be serialized with json.
That json will be deserialized, an used as **kargs in you AJAX function.

http://github.com/jorgebastida/django-dajaxice/blob/master/dajaxice/core/DajaxiceRequest.py#L216

Your serialize(false) return an string. If you change serialize(false) to serialize(true), Prototype will return an object.

Hope this help you
