### ISSUE TITLE
Form example doesn't work in Django 1.0.1

### ISSUE THREAD

**Issue by gerdemb** [jorgebastida/django-dajax#8]
Not sure if something changed a newer version of Django, but this code doesn't work for me in Django 1.0.1:

http://dajaxproject.com/fullform/

form = ExampleForm(form)

I had to decode the URI string into a dictionary first like this:

```
qd = QueryDict(form)
form = EmailForm(qd)
```

**Comment by jorgebastida** [comment]
Hi gerdemb,
Seems that this is the same problem reported in:
http://github.com/jorgebastida/django-dajax/issues/closed#issue/7

If you serialize the form as an object, dajaxice will correctly decode the arguments, and that conversion wouldn't be necessary.

Hope this helps you
