### ISSUE TITLE
Django full form example; jQuery 1.4 support?

### ISSUE THREAD

**Issue by ghost** [jorgebastida/django-dajax#9]
The example on http://dajaxproject.com/fullform/ is broken.

One problem is that the example code that's displayed under "html" doesn't include the <script> needed to serialize the form data and ship it off to the server.

Another is that Dajax/Dajaxice isn't working for me, for jQuery 1.4.2. I get a "process_form() takes exactly 2 arguments (1 given)" traceback on the server. The call I'm using is 

 <script type="text/javascript" charset="utf-8">
  function send_form(){ 
  data = $('#addsection_form').serialize();
  Dajaxice.hosted.process_form('Dajax.process', {'form': data});
  }
  </script>

Can you give me a hint as to where I should look to find the problem? Or is the problem that jQuery 1.4.2 isn't supported by Dajax?

Thanks!

**Comment by jorgebastida** [comment]
Check this thread in dajaxproject mailing list.
http://groups.google.com/group/dajaxproject/browse_thread/thread/af1c291d2fbf37f2

jQuery hasn't a form serialize to object util. Fatrix solve the lack using this code:
http://github.com/cowboy/jquery-misc/blob/master/jquery.ba-serializeobject.js

Hope this help you
